version: 2.1

jobs:
  build:
    docker:
      - image: node:lts
    working_directory: ~/react-hooks
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn run tsc
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    docker: 
      - image: node:lts
    working_directory: ~/react-hooks
    steps:
      - attach_workspace:
          at: ~/react-hooks
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/

            